updating run script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -38,13 +38,21 @@ if [ ! -r ${JAR_PATH} ]; then
     curl -L ${REPO}/${GROUP_PATH}/${ARTIFACT}/${VERSION}/${JAR} > ${JAR_PATH}
 fi
 
-if [ ! -f ${LOCAL_FOLDER}/application.properties ]; then
+if [ ! -f ${LOCAL_INSTALL_PATH}/application.properties ]; then
     echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
-    echo "!! ${LOCAL_FOLDER}/application.properties not found. !!" 1>&2
+    echo "!! ${LOCAL_INSTALL_PATH}/application.properties not found. !!" 1>&2
     echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
     echo "" 1>&2
     echo "Running application with DEFAULTS. (This will probably not work)" 1>&2
     echo "" 1>&2
+fi
+
+if [ ! -f ~/.aws/credentials ]; then
+    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
+    echo "!! ${HOME}/.aws/credentials not found. Please configure. !!" 1>&2
+    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
+    echo "" 1>&2
+    exit 1
 fi
 
 if [ -r ${JAR_PATH} ]; then
